### ISSUE TITLE
Have configured cmp-npm but it is not showing suggestions in cmp window

### ISSUE THREAD

**Issue by snikoletopoulos** [David-Kunz/cmp-npm#10]
I have added configurations but I don't get suggestions in package.json files

![image](https://github.com/David-Kunz/cmp-npm/assets/78855607/a3e71ba4-1be9-4959-ba0a-76ff9a31de46)

![image](https://github.com/David-Kunz/cmp-npm/assets/78855607/19a3cf55-9f4b-4eff-b82a-335b469c85cd)
(the virtual text is from copilot)

**Comment by David-Kunz** [comment]
Hi @snikoletopoulos ,

Do you have `npm` installed? Internally it uses the command `npm info <name> versions --json` and `npm search --no-description --parseable` to query the sources.

Could you run those commands manually to see if they work?

Thanks and best regards,
David

**Comment by snikoletopoulos** [comment]
Hello @David-Kunz ,

Thank you for you fast response.
i tried both commands with `next` as name and both worked.

![image](https://github.com/David-Kunz/cmp-npm/assets/78855607/81c2beb7-bf69-4860-be61-531a279c7d99)

![image](https://github.com/David-Kunz/cmp-npm/assets/78855607/0525499d-0c07-4de4-b409-ce0d9a0ddadc)

Let me know if you want me to try something else.

**Comment by David-Kunz** [comment]
Thanks for checking, @snikoletopoulos !

Maybe you could add a few print statements in your installed package (the location is set by your package manager), just to check that the right commands are executed, e.g. [here](https://github.com/David-Kunz/cmp-npm/blob/e5753b6103ce4cf887233142fa9f31b2d13b42f2/lua/cmp-npm/init.lua#L36).

Could you try that out? Then we'd know more!

**Comment by snikoletopoulos** [comment]
I didn't change anything else but when I put a print it started working.

However i noticed that when i type `next` in package.json, it initially does not find the package.
![image](https://github.com/David-Kunz/cmp-npm/assets/78855607/fc167d50-8b8f-4183-b5fe-711455526389)

If i close cmp and reopen it it find it fine tho.
![image](https://github.com/David-Kunz/cmp-npm/assets/78855607/6a6aebbd-4c29-447d-9e71-7084f533bf69)

Do you think that's a bud? Should I open a new issue?

Thank you for you help

**Comment by David-Kunz** [comment]
Hi @snikoletopoulos ,

Thanks for the update! I'm afraid there's not much I can do, I just forward it to the `npm` command, maybe there's some problem there.

Best regards,
David

**Comment by doctorfree** [comment]
I had the same problem and resolved it by not lazy loading `cmp-nvm`. Not sure why this worked so maybe it is not the right fix for `lazy.nvim` users but it worked for me:

```lua
  {
    "David-Kunz/cmp-npm",
    lazy = false,
    config = function()
      require('cmp-npm').setup({
        ignore = {},
        only_semantic_versions = true,
      })
    end,
  }
```

**Comment by David-Kunz** [comment]
Hi @doctorfree ,

Thanks so much for this hint! I'll put it in the `README.md`.

Best regards,
David

**Comment by snikoletopoulos** [comment]
For me just having it loading at .json files works as well.
```lua
{
  'David-Kunz/cmp-npm',
  ft = "json",
  dependencies = { 'nvim-lua/plenary.nvim' },
  opts = {},
}
```

**Comment by David-Kunz** [comment]
Thanks @snikoletopoulos , is the `ft = "json"` option required? Would it also work without it?

**Comment by doctorfree** [comment]
If `lazy.nvim` is configured to lazy load by default then it appears the `cmp-npm` plugin configuration must trigger the loading one way or another. Using `ft = "json"` works and, in my opinion, is preferable to `lazy = false`. But either works. My `cmp-npm` config now looks like this:

```lua
  {
    "David-Kunz/cmp-npm",
    ft = "json",
    dependencies = { 'nvim-lua/plenary.nvim' },
    config = function()
      require('cmp-npm').setup({
        ignore = {},
        only_semantic_versions = true,
      })
    end,
  }
```

**Comment by David-Kunz** [comment]
Awesome, thanks @doctorfree , I'll put it in the readme!
