### ISSUE TITLE
Package version completion

### ISSUE THREAD

**Issue by coffebar** [David-Kunz/cmp-npm#7]
I specifically made long pauses in the video, but for some reason it does not work properly.

[rec.webm](https://user-images.githubusercontent.com/3100053/202910713-5db05370-c92a-42ca-86be-a55624a601f8.webm)

[my simple config](https://github.com/coffebar/dotfiles/commit/40ff862abe093a075e4e999d0a05c7aedfe7ef76)

**Comment by David-Kunz** [comment]
Hi @coffebar ,

Thanks for reaching out to me. I tried your specific example, but for me it works properly:
![Screenshot 2022-11-21 at 09 15 19](https://user-images.githubusercontent.com/1009936/202999052-ef11ffb9-b4d7-46c8-95fd-408bf9244721.png)

Does your auto completion work for other completion sources?

Thanks and best regards,
David

**Comment by coffebar** [comment]
I tried to find the reason why it doesn't work for me, but I came to the conclusion that, the hints for versions and packages work the same.
Sometimes it works, sometimes it doesn't. Perhaps it can be related to the way npm produces results, if it is slow, and its slow responses somehow do not allow to produce any results at all.

I measured the npm response time with the "time" command and noticed that sometimes it takes up to 2 seconds.
Also, I noticed that the "--no-description" option does not affect what _npm search_ outputs.

If there are no ideas, You can close this issue

**Comment by David-Kunz** [comment]
Thanks for the info @coffebar !
