### ISSUE TITLE
Only show latest version

### ISSUE THREAD

**Issue by uloco** [David-Kunz/cmp-npm#8]
Would it be possible to add a config option to only show the latest version?
This would replicate the behaviour of VSCode and already solve my issues with the sorting not being completely correct.

Say the latest version is `1.2.3`, vscode shows these three completions:
```
1.2.3
^1.2.3
~1.2.3
```
in that order.

What do you think about it?

**Comment by uloco** [comment]
You could get the latest version of a package like so:
```
npm info <package-name> version
```
Although I don't know what minimum npm version is needed for this command. I am on 8.14.0 currently.

**Comment by David-Kunz** [comment]
Hi @uloco,

That's a great idea!

Would you be interested in creating a PR?

**Comment by uloco** [comment]
Yea I'd like to give it a try. Thanks :)

**Comment by David-Kunz** [comment]
Thanks so much, @uloco , great contribution!
